name: Update My IPTV
on:
  workflow_dispatch: # ئەمە ڕێگەت دەدات بە دەست ئیشی پێ بکەیت

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create File
        run: |
          echo "#EXTM3U" > koyar.m3u
          echo "#EXTINF:-1, AVA Sport" >> koyar.m3u
          echo "https://p-9-1.as.iptv.ovh/AVA-Sport/index.m3u8" >> koyar.m3u

      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add koyar.m3u
          git commit -m "First Step: Stable Link" || exit 0
          git push
